In [1]:
print("hello mishika")


hello mishika


In [ ]:
import numpy
import pandas
print("numpy:", numpy.__version__)
print("pandas:", pandas.__version__)

numpy: 2.5.0
pandas: 3.0.3


: 

In [1]:
import numpy as np
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [ ]:
import numpy as np
v = np.array([[1, 2, 3], [5, 6, 7]])
print(v)
print(type(v))
print(v.shape)


[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
n= np.array([[1, 2, 3], [8, 6, 7]])
m= np.array([[1, 4, 3], [5, 6, 7]])
t= np.array([n, m])
print(t)
print(t.shape)


[[[1 2 3]
  [8 6 7]]

 [[1 4 3]
  [5 6 7]]]
